### ISSUE TITLE
Unable to map group information through privacyIDEA to SimpleSAMLphp

### ISSUE THREAD

**Issue by reardencode** [privacyidea/simplesamlphp-module-privacyidea#6]
I'm trying to switch an LDAP integration for simpleSAMLphp over to privacyIDEA for faster, more secure login.  So far I haven't been able to get any LDAP group information propagated to the simpleSAML side.  

I'm open to pretty much any idea you may have in terms of how to configure simpleSAMLphp + privacyIDEA so that LDAP group membership can be used to control access to SAML SPs.

**Comment by reardencode** [comment]
@cornelinux Any ideas?

**Comment by cornelinux** [comment]
This in fact is no matter of the simplesaml plugin than rather of the privacyidea server itself.
I.e. you need to get information out from the /validate/samlcheck endpoint.

This was added in this commit:
https://github.com/privacyidea/privacyidea/commit/d6fe070ca7aaf04263164fa1c35b1fc644749db5

I.e. you would need to extend the LDAP attribute mapping to add the desired LDAP attribute in the /validate/samlcheck response and than map this to your SAML attributes.

I am closing this ticket, since it is better located at privacyidea/privacyidea. 

Probably this will not provide you with a group **list** anyway.
You are welcome to check this out with the latest github commit.
