### ISSUE TITLE
Push token support

### ISSUE THREAD

**Issue by NuvandaPV** [privacyidea/simplesamlphp-module-privacyidea#68]
We should add support for push tokens.

**Comment by fredreichbier** [comment]
#72 looks fine for me for a first step to get Push token functionality working.

But I feel we currently do not adhere to our [specification](https://github.com/privacyidea/privacyidea/wiki/concept%3A-PushToken#polling-endpoint-for-application): We use the polling endpoint only to check when to perform our *actual* second authentication step. The second authentication step of the push token implementation currently seems to perform a request to ``/validate/samlcheck``. This *does* work, but it's not what the specification describes. But as discussed in https://github.com/privacyidea/privacyidea/issues/1838, we're currently not entirely sure if the specification should be changed :)

More importantly, we should check whether the simpleSAMLphp plugin allows the user to provide a transaction ID via a request parameter. This would be problematic, because ``/validate/samlcheck`` does not delete the queried transaction, so we would currently allow re-authentication with an older transaction. @NuvandaPV do you have the time to check this? If not, I can have a look.

**Comment by NuvandaPV** [comment]
As far as I understand setting this up to log in the user without an additional call to `/validate/samlcheck` would require adding a new endpoint to privacyidea (something like `/token/samlchallenges`), that returns the saml-attributes this plugin requires. Not sure if we want to add another endpoint though, if we can get away without the additional complexity.

**Comment by fredreichbier** [comment]
Ah yes, I think you're right. This is a good thing to keep in mind, I've added a note to https://github.com/privacyidea/privacyidea/issues/1838.

**Comment by NuvandaPV** [comment]
Fixed #74
